### ISSUE TITLE
FontAwesome Icons aren't loading 

### ISSUE THREAD

**Issue by ericconrad** [johnshopkins/communications#6]
![screen shot 2016-02-03 at 7 54 32 pm](https://cloud.githubusercontent.com/assets/3170279/12802254/87ba0cae-cab0-11e5-9478-1065568710de.png)
![screen shot 2016-02-03 at 7 54 40 pm](https://cloud.githubusercontent.com/assets/3170279/12802255/87bbbc52-cab0-11e5-80e7-f9efea0b676e.png)

**Comment by ericconrad** [comment]
Didn't notice before because it was loading the font off of my machine. SHAME ERIC 🔔🔔🔔

**Comment by jenwachter** [comment]
Nah, this was me of course.

In the shared fonts repo, I updated font awesome because we needed the newest icons for jhu.edu. To make font awesome work, at some point we updated one of font awesome's core files to change a variable (`$fa-font-path`). I only noticed this because when I updated font awesome, it no longer worked.

Instead of changing this variable in the font awesome core files, it should be changed in our individual projects (jhu, hub, communications, etc...) I made that change on jhu.edu, but totally forgot about communications.

It's only been broken since you updated the studio page copy, so nbd.
